# Generated by Django 3.1.4 on 2020-12-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=30)),
                ('element', models.CharField(choices=[('fire', '火'), ('ice', '氷'), ('tree', '木'), ('light', '光'), ('dark', '闇')], max_length=10)),
            ],
        ),
    ]
