# Generated by Django 3.1.4 on 2020-12-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0002_remove_character_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='Stars',
            field=models.SmallIntegerField(default=3),
        ),
    ]
