# Generated by Django 3.1.4 on 2020-12-16 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0003_character_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='Favorability_rating',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='Level',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='character',
            name='element',
            field=models.CharField(choices=[('fire', '火'), ('ice', '氷'), ('tree', '木'), ('light', '光'), ('dark', '闇')], default='fire', max_length=10),
        ),
        migrations.AddField(
            model_name='character',
            name='mod_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
