# Generated by Django 3.1.4 on 2020-12-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0004_auto_20201216_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='element',
            field=models.CharField(choices=[('fire', '火'), ('ice', '氷'), ('tree', '木'), ('light', '光'), ('dark', '闇')], default='火', max_length=10),
        ),
    ]
