# Generated by Django 3.1.4 on 2020-12-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0006_auto_20201216_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='element',
            field=models.CharField(choices=[('fire', '火'), ('ice', '氷')], default='fire', max_length=10),
        ),
    ]
