# Generated by Django 3.1.4 on 2020-12-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0007_auto_20201216_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='element',
            field=models.CharField(max_length=10),
        ),
    ]
