# Generated by Django 3.1.4 on 2020-12-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0008_auto_20201216_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.SmallIntegerField(default=0)),
                ('Part', models.SmallIntegerField(choices=[(1, '武器'), (2, '頭'), (3, '体'), (4, '首'), (5, '指'), (6, '足')])),
            ],
        ),
    ]
