# Generated by Django 3.1.4 on 2020-12-18 06:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0009_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='equipment',
            name='atk',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='atk_rate',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='defence',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='defence_rate',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='hit',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='hp',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='hp_rate',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='mod_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='equipment',
            name='res',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='speed',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='Stars',
            field=models.SmallIntegerField(choices=[(1, '☆☆☆'), (2, '☆☆☆☆'), (3, '☆☆☆☆☆'), (4, '☆☆☆☆☆☆')]),
        ),
        migrations.AlterField(
            model_name='character',
            name='element',
            field=models.SmallIntegerField(choices=[(1, '火'), (2, '水'), (3, '木'), (4, '光'), (5, '闇')]),
        ),
    ]
