# Generated by Django 3.1.4 on 2020-12-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0010_auto_20201218_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='cri_dmg',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='cri_rate',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='Level',
            field=models.SmallIntegerField(choices=[(1, 'under85'), (2, '85'), (3, '90')]),
        ),
    ]
