# Generated by Django 3.1.4 on 2020-12-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0011_auto_20201218_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='rare_rank',
            field=models.SmallIntegerField(choices=[(1, 'エピック'), (2, 'レジェンド'), (3, 'レア')], default=1),
        ),
    ]
