# Generated by Django 3.1.4 on 2020-12-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0012_equipment_rare_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='set_option',
            field=models.SmallIntegerField(choices=[(1, '憤怒'), (2, '免疫'), (3, '連携'), (4, '反撃'), (5, '吸収'), (6, '破滅'), (7, '速度'), (8, '抵抗'), (9, '命中'), (10, '会心'), (11, '生命'), (12, '攻撃')], default=1),
        ),
    ]
