# Generated by Django 3.1.4 on 2020-12-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0016_auto_20201218_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='set_option',
            field=models.PositiveSmallIntegerField(choices=[(1, '憤怒'), (2, '免疫'), (3, '連携'), (4, '反撃'), (5, '吸収'), (6, '破滅'), (7, '速度'), (8, '抵抗'), (9, '命中'), (10, '会心'), (11, '生命'), (12, '攻撃'), (13, '防御')], default=7),
        ),
    ]
