# Generated by Django 3.1.4 on 2020-12-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0017_auto_20201219_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='role',
            field=models.SmallIntegerField(choices=[(1, 'ナイト'), (2, 'アサシン'), (3, 'メイジ'), (4, 'プリースト'), (5, 'ウォーリアー')], default=1),
        ),
    ]
